version: "3.7"

x-app-common:
  &app-common
  build:
    context: .
    dockerfile: Dockerfile
  command: tail -f /dev/null
  env_file:
    - .envs/app.env
  volumes:
    - ./src:/app

services:
  sidecar:
    <<: *app-common
    environment:
      - DEBUG=1
    volumes:
      - ./src:/app
      # Extend homes to preserve bash and python history (DX)
      - app-roothome:/root
  
  api:
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    #command: uvicorn api:app --host 0.0.0.0 --port 1722 --reload
    #command: gunicorn -b 0.0.0.0:1722 -w 4 -t 120 -k uvicorn.workers.UvicornWorker --access-logfile /logs/access.log --log-level info api:app  --reload
    image: wisrovi/api_face_recognition:V1.0
    volumes:
      - ./logs:/logs
    #  - ./src:/app
    ports:
      - "1722:1722"

  #mariaDB:     
  #  image: mariadb    
  #  env_file:
  #    - .envs/app.env
  #  volumes:
  #    #- ../mariadb_data:/var/lib/mysql
  #    - mariadb_data:/var/lib/mysql
  #  #ports:
  #  #  - "3306:3306"
  #  healthcheck:
  #    test: [ "CMD", "mysqladmin", "ping", "--silent" ]
  #    interval: 10s
  #    timeout: 10s
  #    retries: 5
  #  restart: always

  #web_mariaDB:
  #  image: phpmyadmin
  #  ports:
  #    - "3307:80"
  #  env_file:
  #    - .envs/app.env
  #  depends_on:
  #    - mariaDB
  #  restart: always

volumes:
  app-apphome:
  app-roothome:
  mariadb_data:
